// Generated by ml/train.py --install-to-app. Do not edit by hand.
import type { ModelMetadata } from './types';

export const bundledModel: number | null = require('../../assets/model/visionglyco.tflite');
export const bundledMetadata: ModelMetadata | null = require('../../assets/model/model_metadata.json');
