"""TFLite export, parity check and installation into the React Native app."""

import json
import shutil
import tempfile
from pathlib import Path

import numpy as np
import tensorflow as tf

MODEL_FILENAME = "visionglyco.tflite"
METADATA_FILENAME = "model_metadata.json"

BUNDLED_MODEL_TS = """\
// Generated by ml/train.py --install-to-app. Do not edit by hand.
import type {{ ModelMetadata }} from './types';

export const bundledModel: number | null = require('../../assets/model/{model}');
export const bundledMetadata: ModelMetadata | null = require('../../assets/model/{metadata}');
"""


def export_tflite(model, out_path, float16=True):
    """Convert a Keras model to TFLite (float16 weights halve the file size)."""
    with tempfile.TemporaryDirectory() as tmp:
        saved = Path(tmp) / "saved_model"
        model.export(str(saved), format="tf_saved_model", verbose=False)
        converter = tf.lite.TFLiteConverter.from_saved_model(str(saved))
        if float16:
            converter.optimizations = [tf.lite.Optimize.DEFAULT]
            converter.target_spec.supported_types = [tf.float16]
        Path(out_path).write_bytes(converter.convert())


def tflite_predict(tflite_path, images):
    interpreter = tf.lite.Interpreter(model_path=str(tflite_path))
    inp = interpreter.get_input_details()[0]
    out = interpreter.get_output_details()[0]
    interpreter.resize_tensor_input(inp["index"], [1, *images.shape[1:]])
    interpreter.allocate_tensors()
    results = []
    for image in images:
        interpreter.set_tensor(inp["index"], image[None].astype(np.float32))
        interpreter.invoke()
        results.append(float(interpreter.get_tensor(out["index"]).reshape(-1)[0]))
    return np.array(results)


def check_parity(model, tflite_path, images, tolerance):
    """Fail loudly if the phone model would disagree with the Keras model."""
    keras_out = model.predict(images, verbose=0).reshape(-1)
    tflite_out = tflite_predict(tflite_path, images)
    max_diff = float(np.max(np.abs(keras_out - tflite_out)))
    if max_diff > tolerance:
        raise RuntimeError(f"TFLite output differs from Keras by {max_diff:.4f} (> {tolerance})")
    return max_diff


def write_metadata(path, metadata):
    Path(path).write_text(json.dumps(metadata, indent=2) + "\n")


def install_to_app(output_dir, app_dir):
    """Copy the model into mobile/assets/model and point the app at it."""
    output_dir, app_dir = Path(output_dir), Path(app_dir)
    assets = app_dir / "assets" / "model"
    assets.mkdir(parents=True, exist_ok=True)
    for name in (MODEL_FILENAME, METADATA_FILENAME):
        shutil.copy2(output_dir / name, assets / name)
    ts_path = app_dir / "src" / "ml" / "bundledModel.ts"
    ts_path.write_text(BUNDLED_MODEL_TS.format(model=MODEL_FILENAME, metadata=METADATA_FILENAME))
    return assets
